// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: shop_service.proto

package shop

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_shop_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shop_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_shop_service_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Headers       map[string]string      `protobuf:"bytes,1,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_shop_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shop_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_shop_service_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResponse) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

type GetTicketOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cookie        string                 `protobuf:"bytes,1,opt,name=cookie,proto3" json:"cookie,omitempty"`
	ItemTitle     string                 `protobuf:"bytes,2,opt,name=item_title,json=itemTitle,proto3" json:"item_title,omitempty"`
	ItemId        string                 `protobuf:"bytes,3,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"` // use this if item_title is not provided
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTicketOrderRequest) Reset() {
	*x = GetTicketOrderRequest{}
	mi := &file_shop_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTicketOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTicketOrderRequest) ProtoMessage() {}

func (x *GetTicketOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shop_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTicketOrderRequest.ProtoReflect.Descriptor instead.
func (*GetTicketOrderRequest) Descriptor() ([]byte, []int) {
	return file_shop_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetTicketOrderRequest) GetCookie() string {
	if x != nil {
		return x.Cookie
	}
	return ""
}

func (x *GetTicketOrderRequest) GetItemTitle() string {
	if x != nil {
		return x.ItemTitle
	}
	return ""
}

func (x *GetTicketOrderRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

type TicketOrder struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IsRefunding     bool                   `protobuf:"varint,1,opt,name=is_refunding,json=isRefunding,proto3" json:"is_refunding,omitempty"`
	OrderId         int32                  `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	OrderSn         string                 `protobuf:"bytes,3,opt,name=order_sn,json=orderSn,proto3" json:"order_sn,omitempty"` // 250812-2-123456
	TicketsName     string                 `protobuf:"bytes,4,opt,name=tickets_name,json=ticketsName,proto3" json:"tickets_name,omitempty"`
	SeatType        int32                  `protobuf:"varint,5,opt,name=seat_type,json=seatType,proto3" json:"seat_type,omitempty"`
	SeatTypeName    string                 `protobuf:"bytes,6,opt,name=seat_type_name,json=seatTypeName,proto3" json:"seat_type_name,omitempty"`
	OrderAmount     string                 `protobuf:"bytes,7,opt,name=order_amount,json=orderAmount,proto3" json:"order_amount,omitempty"`
	RefundAmount    string                 `protobuf:"bytes,8,opt,name=refund_amount,json=refundAmount,proto3" json:"refund_amount,omitempty"`
	AddTime         string                 `protobuf:"bytes,9,opt,name=add_time,json=addTime,proto3" json:"add_time,omitempty"` // 2006-01-02 15:04:05
	OrderStatus     int32                  `protobuf:"varint,10,opt,name=order_status,json=orderStatus,proto3" json:"order_status,omitempty"`
	OrderStatusStr  string                 `protobuf:"bytes,11,opt,name=order_status_str,json=orderStatusStr,proto3" json:"order_status_str,omitempty"`
	Details         string                 `protobuf:"bytes,12,opt,name=details,proto3" json:"details,omitempty"`
	Action          string                 `protobuf:"bytes,13,opt,name=action,proto3" json:"action,omitempty"`
	RowClass        string                 `protobuf:"bytes,14,opt,name=row_class,json=rowClass,proto3" json:"row_class,omitempty"`
	EnableCancel    bool                   `protobuf:"varint,15,opt,name=enable_cancel,json=enableCancel,proto3" json:"enable_cancel,omitempty"`
	Integral        int32                  `protobuf:"varint,16,opt,name=integral,proto3" json:"integral,omitempty"`
	Upgrade         int32                  `protobuf:"varint,17,opt,name=upgrade,proto3" json:"upgrade,omitempty"`
	OrderMovieRight int32                  `protobuf:"varint,18,opt,name=order_movie_right,json=orderMovieRight,proto3" json:"order_movie_right,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TicketOrder) Reset() {
	*x = TicketOrder{}
	mi := &file_shop_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TicketOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketOrder) ProtoMessage() {}

func (x *TicketOrder) ProtoReflect() protoreflect.Message {
	mi := &file_shop_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketOrder.ProtoReflect.Descriptor instead.
func (*TicketOrder) Descriptor() ([]byte, []int) {
	return file_shop_service_proto_rawDescGZIP(), []int{3}
}

func (x *TicketOrder) GetIsRefunding() bool {
	if x != nil {
		return x.IsRefunding
	}
	return false
}

func (x *TicketOrder) GetOrderId() int32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *TicketOrder) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

func (x *TicketOrder) GetTicketsName() string {
	if x != nil {
		return x.TicketsName
	}
	return ""
}

func (x *TicketOrder) GetSeatType() int32 {
	if x != nil {
		return x.SeatType
	}
	return 0
}

func (x *TicketOrder) GetSeatTypeName() string {
	if x != nil {
		return x.SeatTypeName
	}
	return ""
}

func (x *TicketOrder) GetOrderAmount() string {
	if x != nil {
		return x.OrderAmount
	}
	return ""
}

func (x *TicketOrder) GetRefundAmount() string {
	if x != nil {
		return x.RefundAmount
	}
	return ""
}

func (x *TicketOrder) GetAddTime() string {
	if x != nil {
		return x.AddTime
	}
	return ""
}

func (x *TicketOrder) GetOrderStatus() int32 {
	if x != nil {
		return x.OrderStatus
	}
	return 0
}

func (x *TicketOrder) GetOrderStatusStr() string {
	if x != nil {
		return x.OrderStatusStr
	}
	return ""
}

func (x *TicketOrder) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

func (x *TicketOrder) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *TicketOrder) GetRowClass() string {
	if x != nil {
		return x.RowClass
	}
	return ""
}

func (x *TicketOrder) GetEnableCancel() bool {
	if x != nil {
		return x.EnableCancel
	}
	return false
}

func (x *TicketOrder) GetIntegral() int32 {
	if x != nil {
		return x.Integral
	}
	return 0
}

func (x *TicketOrder) GetUpgrade() int32 {
	if x != nil {
		return x.Upgrade
	}
	return 0
}

func (x *TicketOrder) GetOrderMovieRight() int32 {
	if x != nil {
		return x.OrderMovieRight
	}
	return 0
}

type GetTicketCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cookie        string                 `protobuf:"bytes,1,opt,name=cookie,proto3" json:"cookie,omitempty"`
	OrderSn       string                 `protobuf:"bytes,2,opt,name=order_sn,json=orderSn,proto3" json:"order_sn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTicketCodeRequest) Reset() {
	*x = GetTicketCodeRequest{}
	mi := &file_shop_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTicketCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTicketCodeRequest) ProtoMessage() {}

func (x *GetTicketCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shop_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTicketCodeRequest.ProtoReflect.Descriptor instead.
func (*GetTicketCodeRequest) Descriptor() ([]byte, []int) {
	return file_shop_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetTicketCodeRequest) GetCookie() string {
	if x != nil {
		return x.Cookie
	}
	return ""
}

func (x *GetTicketCodeRequest) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

type TicketCode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Qrcode        string                 `protobuf:"bytes,1,opt,name=qrcode,proto3" json:"qrcode,omitempty"`
	QrcodeImage   []byte                 `protobuf:"bytes,2,opt,name=qrcode_image,json=qrcodeImage,proto3" json:"qrcode_image,omitempty"`
	QrcodeExt     string                 `protobuf:"bytes,3,opt,name=qrcode_ext,json=qrcodeExt,proto3" json:"qrcode_ext,omitempty"` // e.g., "png", "jpg", lowercase
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TicketCode) Reset() {
	*x = TicketCode{}
	mi := &file_shop_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TicketCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketCode) ProtoMessage() {}

func (x *TicketCode) ProtoReflect() protoreflect.Message {
	mi := &file_shop_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketCode.ProtoReflect.Descriptor instead.
func (*TicketCode) Descriptor() ([]byte, []int) {
	return file_shop_service_proto_rawDescGZIP(), []int{5}
}

func (x *TicketCode) GetQrcode() string {
	if x != nil {
		return x.Qrcode
	}
	return ""
}

func (x *TicketCode) GetQrcodeImage() []byte {
	if x != nil {
		return x.QrcodeImage
	}
	return nil
}

func (x *TicketCode) GetQrcodeExt() string {
	if x != nil {
		return x.QrcodeExt
	}
	return ""
}

type TicketCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketCode    []*TicketCode          `protobuf:"bytes,1,rep,name=ticket_code,json=ticketCode,proto3" json:"ticket_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TicketCodeResponse) Reset() {
	*x = TicketCodeResponse{}
	mi := &file_shop_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TicketCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketCodeResponse) ProtoMessage() {}

func (x *TicketCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shop_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketCodeResponse.ProtoReflect.Descriptor instead.
func (*TicketCodeResponse) Descriptor() ([]byte, []int) {
	return file_shop_service_proto_rawDescGZIP(), []int{6}
}

func (x *TicketCodeResponse) GetTicketCode() []*TicketCode {
	if x != nil {
		return x.TicketCode
	}
	return nil
}

var File_shop_service_proto protoreflect.FileDescriptor

const file_shop_service_proto_rawDesc = "" +
	"\n" +
	"\x12shop_service.proto\x12\x04shop\"F\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\x87\x01\n" +
	"\rLoginResponse\x12:\n" +
	"\aheaders\x18\x01 \x03(\v2 .shop.LoginResponse.HeadersEntryR\aheaders\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"g\n" +
	"\x15GetTicketOrderRequest\x12\x16\n" +
	"\x06cookie\x18\x01 \x01(\tR\x06cookie\x12\x1d\n" +
	"\n" +
	"item_title\x18\x02 \x01(\tR\titemTitle\x12\x17\n" +
	"\aitem_id\x18\x03 \x01(\tR\x06itemId\"\xd2\x04\n" +
	"\vTicketOrder\x12!\n" +
	"\fis_refunding\x18\x01 \x01(\bR\visRefunding\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x05R\aorderId\x12\x19\n" +
	"\border_sn\x18\x03 \x01(\tR\aorderSn\x12!\n" +
	"\ftickets_name\x18\x04 \x01(\tR\vticketsName\x12\x1b\n" +
	"\tseat_type\x18\x05 \x01(\x05R\bseatType\x12$\n" +
	"\x0eseat_type_name\x18\x06 \x01(\tR\fseatTypeName\x12!\n" +
	"\forder_amount\x18\a \x01(\tR\vorderAmount\x12#\n" +
	"\rrefund_amount\x18\b \x01(\tR\frefundAmount\x12\x19\n" +
	"\badd_time\x18\t \x01(\tR\aaddTime\x12!\n" +
	"\forder_status\x18\n" +
	" \x01(\x05R\vorderStatus\x12(\n" +
	"\x10order_status_str\x18\v \x01(\tR\x0eorderStatusStr\x12\x18\n" +
	"\adetails\x18\f \x01(\tR\adetails\x12\x16\n" +
	"\x06action\x18\r \x01(\tR\x06action\x12\x1b\n" +
	"\trow_class\x18\x0e \x01(\tR\browClass\x12#\n" +
	"\renable_cancel\x18\x0f \x01(\bR\fenableCancel\x12\x1a\n" +
	"\bintegral\x18\x10 \x01(\x05R\bintegral\x12\x18\n" +
	"\aupgrade\x18\x11 \x01(\x05R\aupgrade\x12*\n" +
	"\x11order_movie_right\x18\x12 \x01(\x05R\x0forderMovieRight\"I\n" +
	"\x14GetTicketCodeRequest\x12\x16\n" +
	"\x06cookie\x18\x01 \x01(\tR\x06cookie\x12\x19\n" +
	"\border_sn\x18\x02 \x01(\tR\aorderSn\"f\n" +
	"\n" +
	"TicketCode\x12\x16\n" +
	"\x06qrcode\x18\x01 \x01(\tR\x06qrcode\x12!\n" +
	"\fqrcode_image\x18\x02 \x01(\fR\vqrcodeImage\x12\x1d\n" +
	"\n" +
	"qrcode_ext\x18\x03 \x01(\tR\tqrcodeExt\"G\n" +
	"\x12TicketCodeResponse\x121\n" +
	"\vticket_code\x18\x01 \x03(\v2\x10.shop.TicketCodeR\n" +
	"ticketCode2\xc8\x01\n" +
	"\vShopService\x120\n" +
	"\x05Login\x12\x12.shop.LoginRequest\x1a\x13.shop.LoginResponse\x12@\n" +
	"\x0eGetTicketOrder\x12\x1b.shop.GetTicketOrderRequest\x1a\x11.shop.TicketOrder\x12E\n" +
	"\rGetTicketCode\x12\x1a.shop.GetTicketCodeRequest\x1a\x18.shop.TicketCodeResponseB,Z*github.com/zyfy29/flushbuy-proto/shop;shopb\x06proto3"

var (
	file_shop_service_proto_rawDescOnce sync.Once
	file_shop_service_proto_rawDescData []byte
)

func file_shop_service_proto_rawDescGZIP() []byte {
	file_shop_service_proto_rawDescOnce.Do(func() {
		file_shop_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shop_service_proto_rawDesc), len(file_shop_service_proto_rawDesc)))
	})
	return file_shop_service_proto_rawDescData
}

var file_shop_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_shop_service_proto_goTypes = []any{
	(*LoginRequest)(nil),          // 0: shop.LoginRequest
	(*LoginResponse)(nil),         // 1: shop.LoginResponse
	(*GetTicketOrderRequest)(nil), // 2: shop.GetTicketOrderRequest
	(*TicketOrder)(nil),           // 3: shop.TicketOrder
	(*GetTicketCodeRequest)(nil),  // 4: shop.GetTicketCodeRequest
	(*TicketCode)(nil),            // 5: shop.TicketCode
	(*TicketCodeResponse)(nil),    // 6: shop.TicketCodeResponse
	nil,                           // 7: shop.LoginResponse.HeadersEntry
}
var file_shop_service_proto_depIdxs = []int32{
	7, // 0: shop.LoginResponse.headers:type_name -> shop.LoginResponse.HeadersEntry
	5, // 1: shop.TicketCodeResponse.ticket_code:type_name -> shop.TicketCode
	0, // 2: shop.ShopService.Login:input_type -> shop.LoginRequest
	2, // 3: shop.ShopService.GetTicketOrder:input_type -> shop.GetTicketOrderRequest
	4, // 4: shop.ShopService.GetTicketCode:input_type -> shop.GetTicketCodeRequest
	1, // 5: shop.ShopService.Login:output_type -> shop.LoginResponse
	3, // 6: shop.ShopService.GetTicketOrder:output_type -> shop.TicketOrder
	6, // 7: shop.ShopService.GetTicketCode:output_type -> shop.TicketCodeResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_shop_service_proto_init() }
func file_shop_service_proto_init() {
	if File_shop_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shop_service_proto_rawDesc), len(file_shop_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shop_service_proto_goTypes,
		DependencyIndexes: file_shop_service_proto_depIdxs,
		MessageInfos:      file_shop_service_proto_msgTypes,
	}.Build()
	File_shop_service_proto = out.File
	file_shop_service_proto_goTypes = nil
	file_shop_service_proto_depIdxs = nil
}
